### PR TITLE
Add TomAugspurger to maintainers

### PR DESCRIPTION
**Pull request by mrocklin**
cc @TomAugspurger

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
May need to bump the build number.

**Comment by TomAugspurger** [comment]
@conda-forge-admin rerender

**Comment by TomAugspurger** [comment]
I can take a look at the render failure if you want.

**Comment by mrocklin** [comment]
That would be welcome

**Comment by jrbourbeau** [comment]
Closing as Tom was added in https://github.com/conda-forge/partd-feedstock/pull/12

**Pull request closed without merging**
