### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by jrbourbeau**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jrbourbeau** [comment]
@conda-forge-admin, please rerender

**Comment by jrbourbeau** [comment]
Looking at the logs from https://github.com/conda-forge/partd-feedstock/actions/runs/2843445660, it appears rerendering failed due to `toml` not being installed

```python
ModuleNotFoundError: No module named 'toml'
```

@conda-forge/core any thoughts on how we could fix this?

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by jakirkham** [comment]
Think that failure was fixed by PR ( https://github.com/conda-forge/conda-build-feedstock/pull/183 )

**Comment by jrbourbeau** [comment]
Woo! Thanks @jakirkham

**Pull request merged**
